#!/bin/sh

set -e

case "$1" in
    configure)
        vgcfgbackup >/dev/null 2>&1 || :
        invoke-rc.d lvm2 start || :
        if [ -x /usr/sbin/update-initramfs ]; then
            update-initramfs -u
        fi
    ;;
esac

# Automatically added by dh_installinit
if [ -x "/etc/init.d/lvm2" ]; then
	update-rc.d lvm2 start 26 S . >/dev/null || exit $?
fi
# End automatically added section


exit 0
